### PR TITLE
fix: cis-1.9 Kubernetes policies  5.1.6 audit script

### PR DESCRIPTION
**Pull request by winkrs**
Issue #1654 

This PR is to update CIS 1.9 kubernetes policies 5.1.6 audit script to work when run inside a pod.

### CODE REVIEW

**Review by dereknola — APPROVED** [review]

**Comment by mozillazg** [comment]
cc @andypitcher

**Review by andypitcher — APPROVED** [review]
LGTM, tested the changes in Fedora (bash), the expected check result is equivalent.

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Review by afdesk — APPROVED** [review]
thanks for the contribution!

**Pull request merged**
