### PR TITLE
Modify `1.2.3 Ensure that the DenyServiceExternalIPs is set` in CIS-1.7/1.8

### PR DESCRIPTION
**Pull request by andypitcher**
**Parent:** https://github.com/aquasecurity/kube-bench/issues/1606

**Context:** In CIS-1.7 and CIS-1.8 (master `1.2.3 Ensure that the DenyServiceExternalIPs is set`) the operand is wrong and makes the check to **WARN** even if `--enable-admission-plugins=DenyServiceExternalIPs` is properly set.

This PR makes the following change to master 1.2.3 check for `CIS-1.7` and `CIS-1.8`:

 - op changed from `have` to `has` and removed `bin_op: or`
 - remediation description changed to only include `--enable-admission-plugins`

### CODE REVIEW

**Comment by andypitcher** [comment]
@mozillazg could you review this ? For context, this issue has been added in CIS Workbench for 1.10 Milestone
See: https://workbench.cisecurity.org/tickets/21649 and also the below comment:
image

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by andypitcher** [comment]
@mozillazg @afdesk I've just rebased this PR, IMO we should be good to merge it.

**Review by afdesk — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
