### PR TITLE
remove redundant type conversion

### PR DESCRIPTION
**Pull request by mzmuer**
remove redundant type conversion and replace some parameters with constants

/enhancement

### CODE REVIEW

**Comment by mzmuer** [comment]
@chen-keinan hi, have you considered merging this pr

**Comment by chen-keinan** [comment]
@mzmuer lgtm , please rebase Pr with upstream

**Comment by mzmuer** [comment]
> @mzmuer lgtm , please rebase the PR with upstream

I did rebase, but now it looks like the Files changed a lot. actually, no

**Comment by chen-keinan** [comment]
> > @mzmuer lgtm , please rebase the PR with upstream
> 
> I did rebase, but now it looks like the Files changed a lot. actually, no

you probably rebased too far , maybe it will be easy to create new PR from `main` (close this one) and ping me when its ready

**Pull request closed without merging**
