### PR TITLE
Extend default kubelet configlist to fit to current AWS EKS setups (1.29 and above)

### PR DESCRIPTION
**Pull request by mmuth**
- the latest default Kubernetes setup of AWS has its kubelet config path in the added location. Proposing to extend the list of scanned paths in order to make kube-bench execution more painless and "quick start like" in default setups.
- this should fix https://github.com/aquasecurity/kube-bench/issues/1636

### CODE REVIEW

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by mmuth** [comment]
@chen-keinan could you also take a look on this? thanks :)

**Comment by mozillazg** [comment]
@chen-keinan ping~

**Review by afdesk — APPROVED** [review]
thanks for the contribution!

**Pull request merged**
