### PR TITLE
Update aks-1.0 to match official CIS Azure Kubernetes Service (AKS) Benchmark v1.0.0

### PR DESCRIPTION
**Pull request by mozillazg**
[《CIS Azure Kubernetes Service (AKS) Benchmark v1.0.0》](https://workbench.cisecurity.org/benchmarks/6347)

Fixes https://github.com/aquasecurity/kube-bench/issues/984
Fixes https://github.com/aquasecurity/kube-bench/discussions/968
Fixes https://github.com/aquasecurity/kube-bench/discussions/937

### CODE REVIEW

**Review by yoavrotems — CHANGES_REQUESTED** [review]
Thanks for contributing, I know there is an issue with empty remediation section in the CIS but lets maybe try to have there something, I suggested to have a different fields there which are not remediation but explaining the logic with the test. 
Maybe we should consider use "No remediation" instead because this is the most correct one but I'm not sure this is the best option. 
WDYT?

**Comment by mozillazg** [comment]
@yoavrotems 

Yes, having empty remediation isn't a good user experience.

+1 for `No remediation`.
Because the data which is picked from other fields is not 100% suitable for use as remediation, even though it may explain the logic with the test. and the `No remediation` matches the origin cis benchmark.

**Comment by yoavrotems** [comment]
OK then lets go with it, `no remediation` 😸

**Comment by mozillazg** [comment]
@yoavrotems Thanks for your review! Please check again.

**Review by yoavrotems — APPROVED** [review]

**Review by yoavrotems — APPROVED** [review]
LGTM

**Pull request merged**
