### PR TITLE
Code quality improvements

### PR DESCRIPTION
**Pull request by chsatyap**
This PR -

1. Improves empty string test (`len` vs `str == ""`)
2. Converts `fmt.Sprintf` to string literal and `Printf` to `Print` where possible (as the dynamic args are missing!)

Find the other issues found here - [https://deepsource.io/gh/chsatyap/kube-bench/issues/?category=all](https://deepsource.io/gh/chsatyap/kube-bench/issues/?category=all)

This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/aquasecurity/kube-bench).
You can also look at the [docs](https://deepsource.io/docs/guides/quickstart.html) for more details. Do let me know if I can be of any help!

### CODE REVIEW

**Review by lizrice — CHANGES_REQUESTED** [review]
The changes do improve readability so I'd be happy to take them, thank you! But I don't think we will be using the deep source service at this time so I would prefer not to add the toml file. (The toml file appears to have the wrong import path anyway?)

**Comment by chsatyap** [comment]
Alright! I'll drop the config file and retain the improvements only.

**Review by lizrice — APPROVED** [review]
lgtm, thanks!

**Review by lizrice — APPROVED** [review]
approving my own merge :-D

**Pull request merged**
