### PR TITLE
kube-bench failed to scan Openshift platform. Check if the platform i…

### PR DESCRIPTION
**Pull request by nshauli**
…s Openshift and get the oc version

### CODE REVIEW

**Comment by nshauli** [comment]
When kube-bench starts it first reads the generic cfg/config.yaml and then merges in the config.yaml of the relevant version if there is one. After that it checks if all the binaries needed for the test are available, if not it exists with error. In case of ocp it does the same, first reads cfg/config.yaml and then merges in ocp-3.10/config.yaml, but then it fails when it runs the executables check because of cfg/config.yaml which requires kubelet which is unavailable on Openshift platforms. It uses oc. So, I moved the ocp config file to be generic for all ocp future versions and if will need a cfg file for specific version, we should add it to the version folder exactly like we do for kubernetes. I verified it on openshift and it works fine.

**Comment by ttousai** [comment]
@nshauli you are correct about how kube-bench works with config.yaml files.

kube-bench can automatically detect which version of kubernetes you are running via kubectl (which is where your problem is), however you can also manually specify which k8s distro/version your cluster is running with the `--version` .

For example on OCP (we currently support only OCP 3.10) the kube-bench command will look like
`./kube-bench master --version ocp-3.10`

I think your idea for adding support to auto-detect OCP is a good one and we may consider, but for now you can run kube-bench on OCP using some `--version`.

@lizrice  I also think we should consider adding a `list` command to list k8s versions/distros kube-bench support. WDYT?

**Comment by nshauli** [comment]
@ttousai I agree with you about the --version option, but then I have to run the command as follows:
./kube-bench node --json --version ocp-3.10 --config cfg/ocp-3.10/config.yaml 
otherwise it wont work since kube-bench reads cfg/config.yaml before it reads cfg/ocp-3.10/config.yaml unless a config file path is provided. For Kubernetes we just run 
./kube-bench node --json
and kube-bench finds the version and the right config file by itself, so I just made the exact change for opnshift. In order to run with version as a parameter, the aqua enforcer needs to do it by itself, but I think that since kube-bench is a standalone module, it should be able to automatically calculate the version as same as it does it for Kubernetes.

@lizrice the functionality I have added for ocp version auto-detection is minimal and works exactly like in case of Kubernetes. Actually I didn't change the general kube-bench design.

**Comment by ttousai** [comment]
@nshauli you don't  have to specify `--config cfg/ocp-3.10/config.yaml` , I run the command I shared earlier for ocp-3.10 benchmarks and had no problems. I will really appreciate it if you could run the command and share your output.

```
./kube-bench master -v2 --version ocp-3.10 -c 1.5.9
I0221 20:02:53.540839   69030 util.go:132] Looking for config for version ocp-3.10
I0221 20:02:53.541114   69030 util.go:137] Looking for config file: cfg/ocp-3.10/master.yaml
I0221 20:02:53.541338   69030 common.go:65] Using benchmark file: cfg/ocp-3.10/master.yaml
I0221 20:02:53.542144   69030 common.go:77] Using config file: cfg/ocp-3.10/config.yaml
I0221 20:02:53.561628   69030 util.go:112] Component apiserver uses running binary openshift start master api
I0221 20:02:53.581714   69030 util.go:112] Component scheduler uses running binary openshift start master controllers
I0221 20:02:53.595497   69030 util.go:112] Component controllermanager uses running binary openshift start master controllers
I0221 20:02:53.609797   69030 util.go:112] Component etcd uses running binary etcd
I0221 20:02:53.630644   69030 util.go:57] [ps -C flanneld -o cmd --no-headers]: exit status 1
I0221 20:02:53.630778   69030 util.go:284] executable 'flanneld' not running
I0221 20:02:53.630810   69030 util.go:110] Component flanneld not running
I0221 20:02:53.630955   69030 util.go:189] Using default config file name '/etc/origin/master/master-config.yaml' for component apiserver
I0221 20:02:53.631030   69030 util.go:189] Using default config file name '/etc/origin/master/master-config.yaml' for component scheduler
I0221 20:02:53.631132   69030 util.go:189] Using default config file name '/etc/origin/master/master-config.yaml' for component controllermanager
I0221 20:02:53.631183   69030 util.go:196] Component etcd uses config file '/etc/etcd/etcd.conf'
I0221 20:02:53.631245   69030 util.go:189] Using default config file name '/etc/sysconfig/flanneld' for component flanneld
I0221 20:02:53.631269   69030 util.go:189] Using default config file name '/etc/kubernetes/config' for component kubernetes
I0221 20:02:53.631293   69030 util.go:223] Missing service file for apiserver
I0221 20:02:53.631316   69030 util.go:223] Missing service file for scheduler
I0221 20:02:53.631414   69030 util.go:223] Missing service file for controllermanager
I0221 20:02:53.631453   69030 util.go:223] Missing service file for etcd
I0221 20:02:53.631494   69030 util.go:223] Missing service file for flanneld
I0221 20:02:53.631514   69030 util.go:223] Missing service file for kubernetes
I0221 20:02:53.631571   69030 util.go:362] Substituting $controllermanagerbin with 'openshift start master controllers'
I0221 20:02:53.631617   69030 util.go:362] Substituting $etcdbin with 'etcd'
I0221 20:02:53.631696   69030 util.go:362] Substituting $flanneldbin with 'flanneld'
I0221 20:02:53.631742   69030 util.go:362] Substituting $apiserverbin with 'openshift start master api'
I0221 20:02:53.631764   69030 util.go:362] Substituting $schedulerbin with 'openshift start master controllers'
I0221 20:02:53.631783   69030 util.go:362] Substituting $flanneldconf with '/etc/sysconfig/flanneld'
I0221 20:02:53.631804   69030 util.go:362] Substituting $kubernetesconf with '/etc/kubernetes/config'
I0221 20:02:53.631823   69030 util.go:362] Substituting $apiserverconf with '/etc/origin/master/master-config.yaml'
I0221 20:02:53.632102   69030 util.go:362] Substituting $schedulerconf with '/etc/origin/master/master-config.yaml'
I0221 20:02:53.632138   69030 util.go:362] Substituting $controllermanagerconf with '/etc/origin/master/master-config.yaml'
I0221 20:02:53.632178   69030 util.go:362] Substituting $etcdconf with '/etc/etcd/etcd.conf'
I0221 20:02:53.632202   69030 util.go:362] Substituting $apiserversvc with 'apiserver'
I0221 20:02:53.632245   69030 util.go:362] Substituting $schedulersvc with 'scheduler'
I0221 20:02:53.632265   69030 util.go:362] Substituting $controllermanagersvc with 'controllermanager'
I0221 20:02:53.632286   69030 util.go:362] Substituting $etcdsvc with 'etcd'
I0221 20:02:53.632308   69030 util.go:362] Substituting $flanneldsvc with 'flanneld'
I0221 20:02:53.632327   69030 util.go:362] Substituting $kubernetessvc with 'kubernetes'
[INFO] 1 Master Node Security Configuration
[INFO] 1.5 Etcd
[PASS] 1.5.9 Ensure that a unique Certificate Authority is used for etcd (Not Scored)

== Summary ==
1 checks PASS
0 checks FAIL
0 checks INFO
0 checks WARN[root@lizocp310-master-0 kube-bench]# 
```

**Comment by nshauli** [comment]
@ttousai 
[aqua@ocp2152-node-0 kube-bench]$ ./kube-bench node -v2 --version ocp-3.10 -c 1.5.9
I0221 22:30:10.772645    8538 util.go:118] Looking for config for version ocp-3.10
I0221 22:30:10.772709    8538 util.go:123] Looking for config file: cfg/ocp-3.10/node.yaml
I0221 22:30:10.772754    8538 common.go:65] Using benchmark file: cfg/ocp-3.10/node.yaml
I0221 22:30:10.773056    8538 common.go:77] Using config file: cfg/ocp-3.10/config.yaml
I0221 22:30:10.786601    8538 util.go:43] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0221 22:30:10.786676    8538 util.go:270] executable 'hyperkube kubelet' not running
I0221 22:30:10.800991    8538 util.go:43] [ps -C kubelet -o cmd --no-headers]: exit status 1
I0221 22:30:10.801020    8538 util.go:270] executable 'kubelet' not running

need kubelet executable but none of the candidates are running

**Comment by nshauli** [comment]
@ttousai this is the results of my branch. Could you get it and see that it works? you can also specify a config file and it will still work.

[aqua@ocp2152-node-0 kube-bench]$ ./kube-bench node --json
{"id":"2","version":"","text":"Worker Node Security Configuration","node_type":"node","tests":[{"section":"er":"2.1.1","test_desc":"Ensure that the --allow-privileged argument is set to false (Scored)","type":"skipr":"2.1.2","test_desc":"Ensure that the --anonymous-auth argument is set to false (Scored)","type":"skip",""2.1.3","test_desc":"Ensure that the --authorization-mode argument is not set to AlwaysAllow (Scored)","typnfig.yaml and remove authorization-mode under\nkubeletArguments in /etc/origin/node/node-config.yaml or setnumber":"2.1.4","test_desc":"Ensure that the --client-ca-file argument is set as appropriate (Scored)","typnfig.yaml and remove any configuration returned by the following:\ngrep -A1 client-ca-file /etc/origin/nodeenshift/openshift-ansible/blob/release-3.10/roles/openshift_node_group/templates/node-config.yaml.j2#L65\nTConfig.\n"],"status":"PASS","actual_value":"","scored":true},{"test_number":"2.1.5","test_desc":"Ensure thait the Openshift node config file /etc/origin/node/node-config.yaml and removed so that the OpenShift defaur":"2.1.6","test_desc":"Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Score/node-config.yaml and set the streaming-connection-timeout\nvalue like the following in node-config.yaml.\natus":"PASS","actual_value":"","scored":true},{"test_number":"2.1.7","test_desc":"Ensure that the --protect],"status":"INFO","actual_value":"","scored":true},{"test_number":"2.1.9","test_desc":"Ensure that the --kecored)","type":"","test_info":["Reset to the OpenShift defaults\n"],"status":"FAIL","actual_value":"","scorde argument is not set (Scored)","type":"skip","test_info":[""],"status":"INFO","actual_value":"","scored":is set to 0 (Scored)","type":"","test_info":["Edit the Openshift node config file /etc/origin/node/node-con],"status":"PASS","actual_value":"","scored":true},{"test_number":"2.1.12","test_desc":"Ensure that the --t)","type":"","test_info":["Reset to the OpenShift default values.\n"],"status":"FAIL","actual_value":"","sc argument is set to 0 (Scored)","type":"","test_info":["Edit the Openshift node config file /etc/origin/nodletArguments section.\n"],"status":"PASS","actual_value":"","scored":true},{"test_number":"2.1.14","test_de (Scored)","type":"","test_info":["Edit the Openshift node config file /etc/origin/node/node-config.yaml an:"","scored":true},{"test_number":"2.1.15","test_desc":"Ensure that the RotateKubeletServerCertificate argunfig file /etc/origin/node/node-config.yaml and set RotateKubeletServerCertificate to true.\n"],"status":"F":4,"info":0,"desc":"Configuration Files","results":[{"test_number":"2.2.1","test_desc":"Ensure that the ku"","test_info":["Run the below command on each worker node.\nchmod 644 /etc/origin/node/node.kubeconfig\n"]esc":"Ensure that the kubelet.conf file ownership is set to root:root (Scored)","type":"","test_info":[""],esc":"Ensure that the kubelet service file permissions are set to 644 or more restrictive (Scored)","type":emd/system/atomic-openshift-node.service\n"],"status":"PASS","actual_value":"644","scored":true},{"test_numto root:root (Scored)","type":"","test_info":[""],"status":"WARN","actual_value":"","scored":false},{"test_re set to 644 or more restrictive (Scored)","type":"","test_info":["Run the below command on each worker noe":"","scored":true},{"test_number":"2.2.6","test_desc":"Ensure that the proxy kubeconfig file ownership isalue":"","scored":false},{"test_number":"2.2.7","test_desc":"Ensure that the certificate authorities file pRun the below command on each worker node.\nchmod 644 /etc/origin/node/client-ca.crt\n"],"status":"FAIL","ahe client certificate authorities file ownership is set to root:root (Scored)","type":"","test_info":[""],"7,"total_warn":4,"total_info":4}

**Comment by ttousai** [comment]
I think I see what the problem is. Note the config for `node.kubelet.bin`. It appears the ocp config.yaml is not the correct one. Replace the contents of `cfg/ocp-3.10/config.yaml` with this and try again:
```
master:
  apiserver:
    bins:
      - openshift start master api
    defaultconf: /etc/origin/master/master-config.yaml

  scheduler:
    bins:
      - openshift start master controllers
    defaultconf: /etc/origin/master/master-config.yaml

  controllermanager:
    bins:
      - openshift start master controllers
    defaultconf: /etc/origin/master/master-config.yaml

  etcd:
    defaultconf: /etc/kubernetes/manifests/etcd.yaml

node:
  kubelet:
    bins:
      - openshift start network
    defaultconf: /etc/kubernetes/kubelet.conf
    defaultsvc: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

  proxy:
    bins:
      - openshift start network
    defaultconf: /etc/kubernetes/addons/kube-proxy-daemonset.yaml
```

**Comment by nshauli** [comment]
@ttousai still doesn't work and actually it cannot work, if you can please read my previous comments. When you don't specify a config file, it first reads cfg/config.yaml which requires kubelet. I don't have kubelet running, I have oc running. This is why it fails. 

[aqua@ocp2152-node-0 kube-bench]$ ./kube-bench node -v2 --version ocp-3.10 -c 1.5.9
I0221 23:05:41.839766   13873 util.go:118] Looking for config for version ocp-3.10
I0221 23:05:41.839824   13873 util.go:123] Looking for config file: cfg/ocp-3.10/node.yaml
I0221 23:05:41.840387   13873 common.go:65] Using benchmark file: cfg/ocp-3.10/node.yaml
I0221 23:05:41.840771   13873 common.go:77] Using config file: cfg/ocp-3.10/config.yaml
I0221 23:05:41.856030   13873 util.go:270] executable 'openshift start network' not running

need kubelet executable but none of the candidates are running

@lizrice I added support for openshift because of a bug. If the code is wrong, doesn't work, wrong design then just let me know and I'll change/fix it, but If it is fine then I think it should be approved and merged. On Kubernetes it works exactly the same.

**Comment by ttousai** [comment]
@nshauli we appreciate your PR but I'll let @lizrice make the call on whether we will merge it or not.

I am trying to better understand the root cause of the problem (I don't agree with your theory obviously because the command works on my OCP-3.10 cluster).

So I will appreciate any effort you can give in assisting me troubleshooting. In the spirit, please share with me the output of the following command on your node:
```
ps -ef | grep node-config
ps -ef | grep kubelet
```

You can email dwa2pac@gmail.com with the output.

**Pull request closed without merging**
