### PR TITLE
Don't use variable in remediation

### PR DESCRIPTION
**Pull request by mozillazg**
These variables are imported via #738 and they should not be used in remediation because of the variables in remediation will not be replaced with actual value.

### CODE REVIEW

**Comment by bjrara** [comment]
@mozillazg Would you mind explaining why they will not be replaced in remediation? Did you use the new config.yaml in the PR to verify? https://github.com/aquasecurity/kube-bench/pull/738/files#diff-ee8f320b6fba120f9fd902cea5c861cfa04980ba75ca380943ce3a17a1f04b67

**Comment by bjrara** [comment]
And also I'd like to understand why it's a **needless** customization. We had real cases that we wanted to use kube-bench to audit our secured clusters, but our kubeconfig files were located in other locations than the default one. Those hard-coded controllermanager and scheduler configurations blocked our validation.

**Comment by bjrara** [comment]
@mozillazg Thanks for the report. The variables should be replaced. The unexpected behavior is caused by the misconfiguration in config.yaml.
Fixed in https://github.com/aquasecurity/kube-bench/pull/758.

**Comment by mozillazg** [comment]
@bjrara Get it.

**Pull request closed without merging**
