### PR TITLE
Fix for GKE 6.5.5 Incorrect Text #854

### PR DESCRIPTION
**Pull request by cberon**
Update text to match CIS GKE Benchmark v1 description

### CODE REVIEW

**Review by yoavrotems — APPROVED** [review]
Good catch thank you

**Comment by yoavrotems** [comment]
@cberon Hi I didn't noticed it was merge into tmp branch, could you make a PR into main?

**Comment by cberon** [comment]
Done, sorry.

**Comment by yoavrotems** [comment]
Where? 
@cberon

**Pull request merged**
