### PR TITLE
Reword README

### PR DESCRIPTION
**Pull request by ttousai**
Some changes and reorganization to the wording of our README file.

### CODE REVIEW

**Comment by lizrice** [comment]
@ttousai I think it's going to be easier to manage small changes one at a time rather than trying to edit the whole readme at once. I really like the idea of some guidelines to help people raise issues, so it would be great to just add those in one PR. But I am not sure why you are reordering other sections?

**Comment by ttousai** [comment]
> @ttousai I think it's going to be easier to manage small changes one at a time rather than trying to edit 
> the whole readme at once.

Our README currently contains a ton of information, but reading through it, I feel the sections don't follow in a natural and helpful way. We also have some information which don't belong (the section on configuration details for example) which I think we can remove. 

The idea behind this PR is to try for a natural flow for new users and to remove old and information which don't belong on the README. 

The content will be arranged in the ff sections:
1. Introduction
2. Getting started: minimum working examples for each supported platform with links to detailed info
3. How to contribute

The current content does not easily lend itself to a piece-by-piece rewording so I'm using this PR as a staging PR for reviews on the layout and content. We can then cherry-pick parts (for example the contribution section which is relatively whole) and apply to the main document in steps like you suggest.

**Comment by lizrice** [comment]
@ttousai is this still in progress or was it covered by #373 ?

**Comment by ttousai** [comment]
@lizrice we can close this ticket if you are happy with the current state of README.md and docs/README.md.

**Pull request closed without merging**
