### PR TITLE
Fixing remediation field for json result

### PR DESCRIPTION
**Pull request by leodotcloud**
Fixes: https://github.com/aquasecurity/kube-bench/issues/278

remediation field is missing in the json result and the actual remediation text shows up in test_info field.

After the fix:
```
./kube-bench master --version 1.13 --json -c 1.1.1 | jq .
{
  "id": "1",
  "version": "1.13",
  "text": "Master Node Security Configuration",
  "node_type": "master",
  "tests": [
    {
      "section": "1.1",
      "pass": 0,
      "fail": 0,
      "warn": 0,
      "info": 0,
      "desc": "API Server",
      "results": [
        {
          "test_number": "1.1.1",
          "test_desc": "Ensure that the --anonymous-auth argument is set to false (Not Scored)",
          "type": "",
          "remediation": "Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--anonymous-auth=false\n",
          "test_info": null,
          "status": "WARN",
          "actual_value": "",
          "scored": false
        }
      ]
    }
  ],
  "total_pass": 0,
  "total_fail": 0,
  "total_warn": 1,
  "total_info": 0
}
```

### CODE REVIEW

**Comment by leodotcloud** [comment]
@lizrice can you please review?

**Comment by yoavAqua** [comment]
Hi @leodotcloud,
Thank you for your contribution :) 
Unfortunately this change cannot be approved since it breaks the current api's behavior.
Automated systems that use this project expect the remediation to be under the test_info field.
Your change is correct, but we still need to keep the project backward compatible.

**Comment by leodotcloud** [comment]
@yoavAqua I understand your point. How about adding the remediation field and leaving `test_info` as is? That way newer projects can adopt the correct field and the api is not broken for older automated systems. This will also open a way for the older automated systems to start migrating to use the right one. I can resubmit the PR with this change. What say?

**Comment by yoavAqua** [comment]
Great

**Comment by leodotcloud** [comment]
After taking care of the review comments:

```
{
  "id": "1",
  "version": "1.13",
  "text": "Master Node Security Configuration",
  "node_type": "master",
  "tests": [
    {
      "section": "1.1",
      "pass": 0,
      "fail": 0,
      "warn": 0,
      "info": 0,
      "desc": "API Server",
      "results": [
        {
          "test_number": "1.1.1",
          "test_desc": "Ensure that the --anonymous-auth argument is set to false (Not Scored)",
          "type": "",
          "remediation": "Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--anonymous-auth=false\n",
          "test_info": [
            "Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--anonymous-auth=false\n"
          ],
          "status": "WARN",
          "actual_value": "",
          "scored": false
        }
      ]
    }
  ],
  "total_pass": 0,
  "total_fail": 0,
  "total_warn": 1,
  "total_info": 0
}
```

**Comment by leodotcloud** [comment]
@yoavAqua can you please review the new version?

**Comment by yoavAqua** [comment]
LGTM, but I don't have permissions to approve

**Comment by leodotcloud** [comment]
@lizrice can you please help with merge?

**Pull request merged**
