### PR TITLE
Update command to build docker to run in EKS cluster

### PR DESCRIPTION
**Pull request by za**
because with the previous command unable to get the argument.

Issue: https://github.com/aquasecurity/kube-bench/issues/1647

### CODE REVIEW

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by za** [comment]
Thanks for the review @mozillazg

**Comment by mozillazg** [comment]
@chen-keinan ping~

**Review by afdesk — APPROVED** [review]
LGTM too! Thanks!

**Pull request merged**
