### PR TITLE
added eks-1.0 cfg and modified job-eks.yaml for node checks

### PR DESCRIPTION
**Pull request by paavan98pm**
Hi Liz and team,

In anticipation of the imminent CIS EKS Benchmark launch, and to help educate customers on assessing against the benchmark using kube-bench, I've added 'eks-1.0' config under /cfg dir, and modified the job-eks.yaml.

Let me know if any other changes are needed for an updated build to support CIS EKS Benchmark assessments through kube-bench. Many thanks.

-Paavan

### CODE REVIEW

**Comment by lizrice** [comment]
Thanks for this @paavan98pm! The CI build is failing currently, looks like the YAML linter is unhappy with some line endings - please could you take a look at that?

**Comment by paavan98pm** [comment]
Thanks, Liz. I'll check and update in the next few hours.

-paavan

**Comment by paavan98pm** [comment]
> This all looks fine. One small addition though - please could you also add a line into the [table on the README where we list the different versions that are supported](https://github.com/aquasecurity/kube-bench/blob/master/README.md#cis-kubernetes-benchmark-support)

Sure, will do in the next commit.

**Comment by paavan98pm** [comment]
> Thanks for this @paavan98pm! The CI build is [failing](https://travis-ci.org/github/aquasecurity/kube-bench/builds/706768598#L1105) currently, looks like the YAML linter is unhappy with some line endings - please could you take a look at that?

Seems like it is passing now. Thanks, Liz!

**Pull request merged**
