### PR TITLE
chore(message): fix wrong PGSQL_DBNAME error message

### PR DESCRIPTION
**Pull request by luis-serra-ki**

### CODE REVIEW

**Comment by mozillazg** [comment]
@luis-serra-ki Thanks for your contribution!

**Review by mozillazg — APPROVED** [review]
LGTM

**Comment by luis-serra-ki** [comment]
@mozillazg what should I do to fix codecov/patch job?

**Comment by mozillazg** [comment]
> @mozillazg what should I do to fix codecov/patch job?

@luis-serra-ki I don't think we can do something to fix it. It's ok for me.

**Review by mozillazg — APPROVED** [review]

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
