### PR TITLE
chore(lint): setup golangci-lint

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by chen-keinan** [comment]
@mmorel-35 ,  LGTM as well , thanks for the contribution , could you please rebase your branch with upstream

**Comment by mozillazg** [comment]
@mmorel-35 Hi, Matthieu, Are still working on this?

**Comment by mmorel-35** [comment]
Hi @mozillazg , I couldn't find the time to work on this lately. I don't know when I'll be able to get back on this so feel free to take it over from now

**Pull request closed without merging**
