### PR TITLE
docs: document --unscored flag

### LINKED ISSUE #1281: --unscored flag is undocumented
**Overview**

The `--unscored` flag is not documented with the other flags:

https://github.com/aquasecurity/kube-bench/blob/main/docs/flags-and-commands.md#flags 

**How did you run kube-bench?**

N/A

**What happened?**

`--unscored` flag is implemented

**What did you expect to happen:**

`--unscored` flag is documented

**Environment** 

**Running processes**

**Configuration files**

**Anything else you would like to add:**

https://github.com/aquasecurity/kube-bench/commit/9f92e81361a1d4b883e81c42e00e588e85db9a11

### PR DESCRIPTION
**Pull request by joebowbeer**
Fixes #1281

### CODE REVIEW

**Comment by joebowbeer** [comment]
@mozillazg can you approve running workflows?

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Review by chen-keinan — APPROVED** [review]

**Comment by chen-keinan** [comment]
@joebowbeer could you please rebase your branch with upstream

**Comment by joebowbeer** [comment]
@chen-keinan branch updated

**Pull request merged**
