### PR TITLE
Updated version of YAML linting PR

### PR DESCRIPTION
**Pull request by lizrice**
Updated version of #487 to cover the new CIS 1.5 test files

Includes a correction to the integration tests

### CODE REVIEW

**Comment by lizrice** [comment]
Build is failing due to a line ending, but all the line ending types are supposed to be valid YAML. Also I didn’t see that issue locally, so suspect the version of yamllint we’re installing is outdated. Let’s see if this build succeeds

**Comment by lizrice** [comment]
Hm, build still failing but I’m pretty sure all line ending types are valid YAML. @imnotjames do you have any thoughts on stopping yamllint from failing on this?

**Comment by imnotjames** [comment]
```
$ yamllint -c ./.yamllint.yaml .
./cfg/cis-1.5/config.yaml
  1:4       error    wrong new line character: expected \n  (new-lines)
The command "yamllint -c ./.yamllint.yaml ." exited with 1.
```

Is this mixing windows and Linux newlines?

Should that be allowed?

I'll have to take a peek at the file when I'm at my laptop.

**Comment by imnotjames** [comment]
After fetching the branch down,

```
file ./cfg/cis-1.5/config.yaml 
./cfg/cis-1.5/config.yaml: ASCII text, with CRLF line terminators
```

This is CRLF - if we want to change everything to be LF it would fix this issue.

**Comment by imnotjames** [comment]
Re-Opened a draft PR that's currently running tests https://github.com/aquasecurity/kube-bench/pull/554

**Comment by lizrice** [comment]
Closed by #554

**Pull request closed without merging**
