### PR TITLE
FIX | k3s-cis-*- CHECK 4.2.1-4.2.3

### PR DESCRIPTION
**Pull request by aprilpear9696**
The check [4.2.1-4.2.3 for k3s-cis-*](https://github.com/aquasecurity/kube-bench/blob/main/cfg/k3s-cis-1.8/node.yaml#L155) is aim to check the node kubelet status. But current test case audit/audit_config commands are targeting kube-apiserver instead of kubelet.
Update the target tests' audit/audit_config command from checking kube-apiserver arguments to checking kubelet ones.

### CODE REVIEW

**Review by afdesk — APPROVED** [review]
@aprilpear9696 
 It seems it makes sense! 
thanks for the contribute!

**Comment by afdesk** [comment]
@mozillazg wdyt?

**Comment by mozillazg** [comment]
cc @andypitcher

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by afdesk** [comment]
merged
@aprilpear9696, @mozillazg thanks!

**Pull request merged**
