### PR TITLE
feat(cis-1.24-microk8s): Add support to CIS-1.24 for microk8s distro

### PR DESCRIPTION
**Pull request by bschimke95**
kube-bench is the main security benchmark in k8s. This PR adds the configs required for the benchmark check to verify CIS-1.24 for microk8s.

This requires the microk8s addon `cis-hardening` to be enabled which is available from version 1.28.
Alternatively, the hardening can manually be applied and verified following the tutorial and steps here: https://microk8s.io/docs/how-to-cis-harden

### test environment
```
➜ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

➜ sudo microk8s version                              
MicroK8s v1.28.1 revision 5916

➜ sudo microk8s enable cis-hardening
Infer repository core for addon cis-hardening
Enabling RBAC
Infer repository core for addon rbac
Enabling RBAC
Reconfiguring apiserver
Restarting apiserver
RBAC is enabled
Copy extra files
Downloading kube-bench
Stopping services
Setting file permissions
Setting API server arguments
Setting controller manager arguments
Setting kubelet arguments
Starting services

CIS hardening configuration has been applied. All microk8s commands require sudo from now on.
Remember to enable this addon on nodes joining the custer.
Inspect the CIS benchmark results with:

  sudo microk8s kube-bench
```

### kube-bench results
https://pastebin.com/7GfwetfC

### CODE REVIEW

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by mozillazg** [comment]
@chen-keinan ping~

**Review by chen-keinan — APPROVED** [review]

**Comment by chen-keinan** [comment]
@bschimke95 could you please rebase your branch with upstream

**Comment by bschimke95** [comment]
@chen-keinan done

**Pull request merged**
