### PR TITLE
Support auto-detect platform when running on EKS or GKE

### LINKED ISSUE #661: Auto-detect platform
Now that we have dedicated CIS Kubernetes benchmarks for EKS and GKE, it would be good if kube-bench auto-detected these platforms and ran the appropriate versions of the tests

### PR DESCRIPTION
**Pull request by mozillazg**
Closes #661

### CODE REVIEW

**Comment by lizrice** [comment]
This is looking good @mozillazg - it's marked as a draft but I wonder if it's ready to merge yet?

**Comment by mozillazg** [comment]
@lizrice There is an issue: this way can't work on EKS because of there isn't kubectl command on the nodes (don't test on GKE yet because of I have some issues which cause me can't create a GKE cluster. Maybe GKE nodes don't include kubectl command too).

**Comment by mozillazg** [comment]
Have tested on GKE and EKS. Ready for review.

**Comment by mozillazg** [comment]
@yoavrotems ping~

**Comment by yoavrotems** [comment]
@mozillazg I will spin a machine and check this PR

**Review by yoavrotems — APPROVED** [review]
LGTM

**Pull request merged**
