### PR TITLE
Adding support for new cpu architecture (ppc64le)

### PR DESCRIPTION
**Pull request by manasiprabhavalkar**
Support ppc64le (IBM Power) architecture. Changed the other 2 files as requested.

### CODE REVIEW

**Review by yoavrotems — APPROVED** [review]
LGTM

**Comment by mozillazg** [comment]
There are some files that need to be updated too:

https://github.com/aquasecurity/kube-bench/blob/d3cbc6447630129ab02d2c77b9418e258ed5a846/.goreleaser.yml#L11-L15

https://github.com/aquasecurity/kube-bench/blob/d3cbc6447630129ab02d2c77b9418e258ed5a846/.github/workflows/publish.yml#L53-L55

**Comment by manasiprabhavalkar** [comment]
Made the necessary changes the 2 files as requested to add support for ppc64le CPU architecture

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Pull request merged**
