### PR TITLE
Remove Master and Node Commands

### PR DESCRIPTION
**Pull request by njgibbon**
Hello,

Issue: https://github.com/aquasecurity/kube-bench/issues/931

Removed usage inline with the issue.

Is there anything else here to be aware of?

### CODE REVIEW

**Comment by yoavrotems** [comment]
Hey thanks for contributing ! I want to leave it open until the next major release

**Comment by chen-keinan** [comment]
@njgibbon thank you for the contribution, could you please rebase your branch with upstream?

**Comment by njgibbon** [comment]
@chen-keinan - Just updated :)

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Comment by chen-keinan** [comment]
LGTM as well , thanks for contributing

**Pull request merged**
