### PR TITLE
Automated testing 1.2.34

### PR DESCRIPTION
**Pull request by DOboznyi**
Added automated testing of Encryption provider configuration. Such script extract provider name from encryption configuration and validate it.

### CODE REVIEW

**Comment by DOboznyi** [comment]
@lizrice @yoavrotems Could you review this PR?

**Comment by DOboznyi** [comment]
@yoavrotems ping

**Comment by DOboznyi** [comment]
@yoavrotems ping

**Review by yoavrotems — CHANGES_REQUESTED** [review]
Hey Im very sorry I reviewed and forgot to press submit

**Comment by DOboznyi** [comment]
@yoavrotems I fixed mentioned issues

**Review by yoavrotems — APPROVED** [review]
Thanks for the contribution, really good job here :) at first I had a concern about the audit because its a bit different then what CIS suggest but afterward its really is what it says in the description part: 

> Get the EncryptionConfig file set for --encryption-provider-config argument. Verify
that aescbc, kms or secretbox is set as the encryption provider for all the desired
resources.

**Pull request merged**
