### PR TITLE
job.yaml: Adding /var/lib/cni mount for proper CIS 1.1.9 and 1.1.10 checking

### PR DESCRIPTION
**Pull request by apolovov**
Adding /var/lib/cni mount in job manifests for proper CIS 1.1.9 and 1.1.0 checking.
It was impossible to pass the checks without the mount. The result is WARN regardless of the actual file permissions on the host.

### CODE REVIEW

**Comment by apolovov** [comment]
@chen-keinan could you review pls?

**Comment by mozillazg** [comment]
@apolovov Could you please sign the CLA? Thanks.

**Comment by apolovov** [comment]
@mozillazg Signed, sorry for the delay.

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
